### PR TITLE
properly sort pagenames by namespace. fixes #308

### LINKED ISSUE #308: Pages in Subnamespaces get same level as Pages in Namespace
Hallo everybody,

I want to create a book of my Howto-Pages in my wiki. The structure I have is the following:
**company:howto:**
This namespace contains a lot of pages, but has also a subnamespace:
**company:howto:sap:**
which again contains a lot of pages.
If I now create a PDF for the complete howto namespace I've thought, that every page being part of a subnamespace is found under its specific namespace. But the PDF contains every page with the same level of hierarchy, f.e.:

1. company:howto:howto1
2. company:howto:subnamespace:howto2
3. company:howto:howto2
4. company:howto:subnamespace:start
5. company:howto:howto3
6. company:howto:subnamespace:howto1
7. company:howto:subnamespace:howto3

You get the point. The result I would've expected is:

1. company:howto:howto1
2. company:howto:howto2
3. company:howto:howto3
4. company:howto:subnamespace:start
4.1. company:howto:subnamespace:howto1
4.2. company:howto:subnamespace:howto1
4.3. company:howto:subnamespace:howto3

Do you have any idea, how I can achieve this?

Beste regards!

### PR DESCRIPTION
**Pull request by splitbrain**
This ensures pages within the same namespace are put together, with the
start page being always first.

I think it would be worth discussing what we actually expect from the natural sort. I would think it should be the same as this, only using natsort as the underlying sort mechanism?

### CODE REVIEW

**Comment by splitbrain** [comment]
Test fails are unrelated and caused by a change in DokuWiki master

**Comment by Klap-in** [comment]
First quick response:
The default start page is `$conf['start']`. However there is also "[Default linking of namespaces](https://www.dokuwiki.org/namespaces#namespace_default_linking)" which act as kind of start page as well. https://github.com/splitbrain/dokuwiki/blob/master/inc/pageutils.php#L73 When do we respect these? (e.g. Indexmenu plugin has even option to select the right one). 

My first feeling is to ignore other than start, because it clutters if people are using them unintentionally.

 if `start` exists, then not `foo` as startpage and normally sorted:
  * foo:start <sorted up
  * foo:a
  * foo:foo < normal sorted
  * foo:page1

 `foo` instead of start (if `start` not exists):
  * foo:foo < sorted up
  * foo:a
  * foo:page1

`foo` at same level as namespace `foo`, is automatically solved, if namespaces are sorted as pages. My feeling is that this sorting order is needed to fix the sorting of sub(sub)namespaces(see next point), side effect: this kind of namespace linking is solved as well.

what about combinations of:
  * a
  * foo
  * foo:start < sorted up
  * foo:a
  * foo:foo < normal sorted
  * foo:page1
  * z

and sub-namespace should be 
  * bar
  * bar:plugin_aa
  * bar:plugin_aa:detail1
  * bar:plugin_aa:detail2
  * bar:plugin_bb
  * bar:plugin_bb:detail1
  * devel
  * devel:aa
  * devel:test
  * devel:test:detail1
 * devel:test:detail2

example:
```php
            ['id' => 'start'],
            ['id' => '01_page'],
            ['id' => '10_page'],
            ['id' => 'bar'],
            ['id' => 'bar:start'],
            ['id' => 'bar:01_page'],
            ['id' => 'bar:10_page'],
            ['id' => 'bar:aa_page'],
            ['id' => 'bar:aa_page:detail1'],
            ['id' => 'bar:zz_page'],
            ['id' => 'foo'],
            ['id' => 'foo:start'],
            ['id' => 'foo:01_page'],
            ['id' => 'foo:10_page'],
            ['id' => 'foo:zz_page'],
            ['id' => 'ns'],
            ['id' => 'ns:ns'],
            ['id' => 'ns:01_page'],
            ['id' => 'ns:10_page'],
            ['id' => 'ns:zz_page'],
            ['id' => 'zz_page'],
```

**Comment by splitbrain** [comment]
@Klap-in quick question: how would a namespace without a start page sort into this?

**Comment by splitbrain** [comment]
I got the sorter to nearly run through your given example. However one thing is a bit tricky. You do not sort up `foo:foo` because `foo:start` exists. This is tricky to do in a sort function alone because we only ever compare two given IDs - I have no knowledge about all other IDs. The only way to implement this would be to actually check the existence of the page on disk. It would make testing more complicated, so I would like to avoid it.

There are two options then: always sort the namspace named page to the front, right after start:

* foo
* foo:start
* foo:foo
* foo:alpha

Or never do it regardless of the existence of a "proper" start page:

* foo
* (foo:alpha:start)
* foo:alpha
* foo:foo

I don't know what to prefer

**Comment by Klap-in** [comment]
My guess is that a few people know and use the foo:foo as start page for foo. I expect also that sorting this foo:foo page, will more often be wrong than right.

So to prevent checking existance of these files, it is fine for me to only sort the foo:start page, and to ignore foo:foo during sorting, so sort it just as a normal page.

**Comment by splitbrain** [comment]
I updated the sorting accordingly. What about:

> I think it would be worth discussing what we actually expect from the natural sort. I would think it should be the same as this, only using `natsort` as the underlying sort mechanism?

**Comment by Klap-in** [comment]
Ah, did spot that question. natsort is just sorting in the number in more logic order, i.e. 1 2 10 14 20 etc (in stead of 1 10 14 2 20)
I prefer natsort.

As 01 02 10 or 1 2 10 are sorted the same, I don't see problems. Recently at more places in DokuWiki natsort is introduced. For me it feels more logic, and less work for the wiki user.

**Comment by splitbrain** [comment]
Okay, I removed the difference between the two modes and always sort naturally.

**Pull request merged**
