### PR TITLE
Upgrade mpdf library

### PR DESCRIPTION
**Pull request by micgro42**
Upgrade the underlying [mpdf](https://github.com/mpdf/mpdf)-library to its current HEAD. This gives us PHP7.1 compatibility and better CSS3 support.

ToDo:
--------
- [x] test PHP 5.6 compatibility
- [x] check in the files from the current mpdf development HEAD
- [x] fix conflicts

### CODE REVIEW

**Comment by micgro42** [comment]
It works under PHP 5.6 and PHP 7.0 as well.

However, I noticed, that while utilizing the PHPFarm, it fails (500) to export a page, if that page has the title (i.e. first headline) `temp`. It works correctly if I change the headline or use my local system.
Unfortunately, the containers error-log appears to be empty.

**Comment by Klap-in** [comment]
Is it still possible to make a tag of dw2pdf plugin with the mpdf6.0 version, so that the https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/releases has that as fallback available as well? (I don't need it at the moment, but could be useful for debugging)

**Comment by splitbrain** [comment]
Yes, that should be possible. I need to figure out what the last commit is with the old mpdf and tag it accordingly.

I'm wondering though why this plugin doesn't have *any* tags. My version upgrade script should usually create tags for each change in the version file. Gotta look into that, too.

**Comment by Klap-in** [comment]
Maybe the upgrade script is not looking in to this repository? last update of plugin.info.txt is already a year ago.

**Comment by splitbrain** [comment]
Ah, the problem is that the plugin is not listed with my email address at dokuwiki.org. I added it manually

**Pull request merged**
