### PR TITLE
Implemented config option for setting the font size.

### PR DESCRIPTION
**Pull request by LarsGit223**
This is a simple change for setting the default font-size for the PDF export. Also see this question from the forum: https://forum.dokuwiki.org/thread/14541.

Kind Regards,
Lars

### CODE REVIEW

**Comment by Klap-in** [comment]
Changes the whole pdf if you change this setting?
or only things like code blocks?

I'm wondering if it is an useful setting for normal users/admins of the dw2pdf plugin to tune. My first impression: it is not. Therefore I'm thinking: is there not an approach for guessing the right default font size from (for example) the default text...

Next guessing is the mPDF plugin already doing in its constructor, but that seems not successfull... 

```php
if (!$default_font_size) { 
		$mmsize = $this->ConvertSize($this->defaultCSS['BODY']['FONT-SIZE']);
		$default_font_size = $mmsize*(_MPDFK);
	}

	if ($default_font) { $this->SetDefaultFont($default_font); }
	if ($default_font_size) { $this->SetDefaultFontSize($default_font_size); }
```

**Comment by LarsGit223** [comment]
No, it changes the whole PDF.

I think the font-size is a very subjective thing. It can differ with the kind of text that you write/export. Also some users might have problems with reading small letters and would like a simple option to make it bigger. And in technical writing I guess that you prefer smaller font-sizes to get more information on the page. Also keep in mind that the layout on an A4 page is different than on the screen. So the user can kind of adopt to that difference by changing the font-size.

And see the post at the forum. There is at least one user who is thinking it would be useful. Then there will be others :-)

And if you keep the default setting, then the document is exported with the same size as before (as far as I noticed in my tests with the DokuWiki template).

**Comment by Klap-in** [comment]
The global scaling of the document is nice.
I'm still wondering why the monospace characters are little large than the arial normal text at the page. Now my guess is that the monospace font available in the dw2pdf plugin is a bit larger than the version used in the browser.

**Comment by LarsGit223** [comment]
I guess the template could still overwrite the font-size if it's using absolute values for font-size. But that usually not be the case.

About monospace I don't know. I remember that I had a similar problem in the ODT plugin. That was related to wrong inheritance of CSS properties. But if they need to have the fonts available in all the sizes, then that might be the problem.

**Comment by Klap-in** [comment]
With the Developer tool I see different kind of font-sizes in the screen style. 
1em, 87.5%, 1.4 (line height..) etc. I don't know how these are interacting with each other (relative vs absolute)

In the print style there is no font-size set at all. So all fontsizes for normal text and code block are from mPDF library (or its fonts).

**Comment by LarsGit223** [comment]
1em means one time the current font-size. If there has not been any absolute specification of the font-size in the CSS on hiting a property value like '1em' then the font-size comes from the browser. So the root default font-size is as set in the browser. So I assume in mPDF you do the same thing if you give a font-size to the constructor. If not, then they set some default value. You need to have this to be able to process relative values like em or percentage values.

If line-height has just a number then that also is just a factor for the current font-size, see https://www.w3schools.com/cssref/pr_dim_line-height.asp.

**Comment by LarsGit223** [comment]
That is what I expected. It is quite unusual to use absolute values I assume. Then you cannot scale your CSS code/template code.

**Comment by Klap-in** [comment]
Thanks for the explanation. I think that if people like to improve the font-size of the code blocks, that I will recommend to create a new pdf template folder with another style file which specifies their desired size.

**Comment by LarsGit223** [comment]
Sounds good :thumbsup:

**Pull request merged**
