### PR TITLE
Check acl, continues export with book_skipforbiddenpages=1 is set

### PR DESCRIPTION
**Pull request by Klap-in**
Default it shows a message which warns that selection contains acl protected pages.
To continue the url parameter `book_skipforbiddenpages=1` is required.

### CODE REVIEW

**Comment by Klap-in** [comment]
Any feedback? This acl checking when exporting pdfs breaks backward compatibility..

**Comment by splitbrain** [comment]
Makes sense to me, but I would offer a button to continue instead of saying "add a parameter to the URL".

**Comment by Klap-in** [comment]
There are 3 ways of triggering a pdf export:
- ?do=export_pdf
- ?do=export_pdfns
- request via bookcreator 

All these urls could be called with a GET. The bookcreator is using POST at the moment.
That POST request is initiated by some javascript stuff. It is not just an url that I can easy extend and put in a button.

The suggestion of Pasting parameter to the url is especially for people that are building that url themself and not via bookcreator.

For `?do=export_pdf` people are already caught by the default 'No access' page.
I think I will simplify the message to: use the 'Skip Forbidden Pages' checkbox.

And that people have to read the manual to discover the existence of this `skipbook_skipforbiddenpages=1` for there self build urls... (not nice for backward compatibility....)

**Comment by Klap-in** [comment]
Or just left out this option. and  just ignore forbidden pages without noticing the user?

**Comment by Klap-in** [comment]
I have chosen to improve message. The only place where it really used is in the dialog of the bookcreator.  The bookcreator has already an checkbox for this parameter, so I think a message is enough.

**Pull request merged**
