### PR TITLE
Update and adjustment to mpdf6.0.

### PR DESCRIPTION
**Pull request by LarsGit223**
As requested the update to mpdf in two separate commits:
- the one labeled as the update only applies to the mpdf folder
- the one labeled as adjustments only applies to dw2pdf code

### CODE REVIEW

**Comment by Klap-in** [comment]
I see you add the examples as well. To reduce the download size these should be exluded from the download archive. I see two options to perform this:
 - The package for dokuwiki is doing this via some git settings, I think it is possible here as well.
 - or just removing the example stuff from this repo.

I think the first option is probably useful for testing purposes.

**Comment by splitbrain** [comment]
the examples created a security issue before, so I would recommend removing them from the repository completely and add them to the gitignore to avoid accidental reading.

**Comment by LarsGit223** [comment]
Done.

**Comment by Klap-in** [comment]
Reading the release announcement [1] and the pdf linked at that forum I understand it is a big update.

[1] http://www.mpdf1.com/forum/discussion/2280/mpdf-6-0-released-with-support-for-complex-scripts

The author warns not to leave old files. With the recommendation to perform a clean installation.
Are you sure you don't leave old stuff?

Can you give an indication of the installation size of the plugin since version 6.0?

**Comment by Klap-in** [comment]
Ok, fast check:
- installation size goes from ~27MB (with version 5.4) to ~107MB (with version 6)
- old stuff seems to be removed, nice!

**Comment by Klap-in** [comment]
Opinions about this installation size?

listing of the directory sizes:
```
lib/plugins/dw2pdf$ du -h mpdf/
8,0K		mpdf/tmp
2,7M	mpdf/iccprofiles
1,3M	mpdf/utils
1,3M	mpdf/classes
6,9M	mpdf/qrcode/data
7,0M	mpdf/qrcode
12K		mpdf/mpdfi/filters
52K		mpdf/mpdfi
1,5M	mpdf/includes
87M		mpdf/ttfonts
508K	mpdf/patterns
8,0K		mpdf/graph_cache
8,0K		mpdf/ttfontdata
668K	mpdf/collations
92K		mpdf/font
104M	mpdf/
```

Do we need qrcode stuff? This is useful to remove i think ( ~14MB)
dw2pdf had a link to the google qr code generator, let see how that is related.

Many fonts are nice and handy for strange situations (it is used by the auto detection of the mpdf). But maybe a selection is also fine... Suggestions welcome.
Suggestions

**Comment by Klap-in** [comment]
http://mpdf1.com/manual/index.php?tid=407

My guess is that instructions like `<barcode code="Your message here" type="QR" class="barcode" size="0.8" error="M" />` triggers the qr stuff. This is (normally?) not included via DokuWiki. So I think we can remove it without loss of functionality.

Does this require an additional check of the html that is inputted in the mpdf, to be sure we remove <barcode> like stuff?

The `@QRCODE@` placeholder is already replaced in action.php by an image generated by a google generator.

**Comment by LarsGit223** [comment]
**Regarding qr code:**
I quickly tested exporting a book with the qr code folder present and without it.
Both works, the result is the same. Qr code is present on the end of the page in both cases.

So I can confirm that the qr folder might be deleted.

**Regarding old stuff:**
I completely deleted the mpdf folder and then copied in the new folder. I did not copy the new mpdf version over the old one. Removed folders/files have been checked in with `git rm`.

**Regarding fonts:**
I don't know which fonts might be dropped. Maybe compare with the previous version and only keep the equal stuff? We maybe should ask in the mailing list who is using dw2pdf with which fonts?

**Regarding size:**
Is the size that critical? The dw2pdf plugin is not bundled with DokuWiki. Should we limit the functionality just to save some megabytes?

Also, on every upcoming update we would have to do this shrinking again.

**Comment by splitbrain** [comment]
re: QRCode - Google Chart Image API was said to go down in April this year. I'm secretly hoping they changed their mind. But if MPDF has builtin QR generation now it might be worth using that instead of requiring an extra HTTP request.

re: size - 100MB is a lot for a DokuWiki plugin. People might experience timeout when downloading it via the extension manager. OTOH, having those fonts is useful for some people. I'm undecided. One way would be to move the fonts to a second plugin 'dw2pdf-fonts', so people could install them separately. Not sure if that's a good idea.

**Comment by LarsGit223** [comment]
re:size
Just to mention it. If I zip compress my local dw2pdf plugin folder with mpdf version 6.0 the size is 54 MB. Still arge but somewhat different from 100 MB. The extension manager will download a zip file right? So we have to deal with 54 MB not 100 MB.

**Comment by Klap-in** [comment]
I think including the current fonts is fine. We can remove/move to additional plugin later as well. When it appear people has real problems with the size.

Do you agree?

For possibilities for reducing package more items are suggested by the author: http://www.mpdf1.com/forum/discussion/2313

I think /utils can be removed as well.
The others are useful at first sight, and are quite small.

I think by using gitignore, shrinking on every upcoming update is prevented.

**Comment by splitbrain** [comment]
agreed

**Comment by Klap-in** [comment]
This pull request is not mergable. I tested a fork of it already a bit.
Can you make it mergable again?

As fallback I have tagged the current state of the plugin (see https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/releases). So I think it fine to merge this into the master, or do you still know issues?

**Comment by LarsGit223** [comment]
What do you mean with "not mergeable"/make it mergable again?

I can only try to re-play the changes in a clean master checkout and create a new pull-request. But if there are merge conflicts then I think these will apear again, or not?

**Comment by Klap-in** [comment]
I guess one of the recent changes conflicts with changes in this PR so a merge with master should fix this.

**Comment by LarsGit223** [comment]
Ahhh...yeah. Done.

**Comment by Klap-in** [comment]
Thanks, this is a big change  :) , so I hope it will not break too much for people...
As backup there is an release with the old mPDF library: 
https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/releases

**Pull request merged**
