### PR TITLE
Add syntax to export namespace to pdf

### PR DESCRIPTION
**Pull request by micgro42**
Add syntax pattern `~~PDFNS>(?:.*?)\|(?:.*?)~~` where the first capture group is the namespace and the second capture group is the name of the pdf.

This syntax pattern is inspired by the already existing pattern `~~PDF:(?:LANDSCAPE|PORTRAIT)~~` which defines the orientation of a page.

A test which tests at least the parser output has been added.

### CODE REVIEW

**Comment by Klap-in** [comment]
Nice idea.

**Comment by Klap-in** [comment]
Today I have changed the url parameters: 

pdftitle => book_title
pdfns_title => book_title
pdfns_ns => book_ns
pdfns_order => book_order
pdfns_depth => book_nsdepth
pdfbook_title => book_title

Temporary an fallback is left for: pdftitle and pdfbook_title
NOT for the pdfns_* parameters

See 177a7d302750f9eaf84b5aa8fad8f4766ea4d74a

If you have more applications of the pdfns export option, you have to update these as well.

-------

@micgro42: Two requests related to this pull request: 
 * please can you update the documentation in the wiki with your new syntax? Thanks!
 * do you know how to enable Travis testing for this repository? There are unittests, but these are not runned online...

**Comment by micgro42** [comment]
* I have updated the documentation
* Since this is @splitbrain's plugin, only he can activate travis on this repository. However you can activate travis for your own fork.

**Comment by splitbrain** [comment]
I enabled travis integration. It should be triggered with the next push

**Comment by Klap-in** [comment]
Does someone create already a config file for Travis? It is missing this file.

**Pull request merged**
